server:
  port: 8081
spring:
  datasource:
    main:
      banner-mode: "off"
    url: jdbc:postgresql://localhost:5432/saferoute_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # O 'validate', 'update', etc.
    show-sql: false
    open-in-view: false
